//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.28 at 11:04:41 AM BRT 
//


package br.unesp.repositorio.base.xmlschema.metadatapatterner;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.unesp.repositorio.base.xmlschema.metadatapatterner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Patterns_QNAME = new QName("http://base.repositorio.unesp.br/XMLSchema/MetadataPatterner", "patterns");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.unesp.repositorio.base.xmlschema.metadatapatterner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Patterns }
     * 
     */
    public Patterns createPatterns() {
        return new Patterns();
    }

    /**
     * Create an instance of {@link Pattern }
     * 
     */
    public Pattern createPattern() {
        return new Pattern();
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Patterns }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://base.repositorio.unesp.br/XMLSchema/MetadataPatterner", name = "patterns")
    public JAXBElement<Patterns> createPatterns(Patterns value) {
        return new JAXBElement<Patterns>(_Patterns_QNAME, Patterns.class, null, value);
    }

}
